apiVersion: invokeroperator.invoker.io/v1alpha1
kind: InvokerDeployment
metadata:
  labels:
    app.kubernetes.io/name: invokerdeployment
    app.kubernetes.io/instance: invokerdeployment-sample
    app.kubernetes.io/part-of: invoker-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: invoker-operator
  name: sample
  namespace: test
spec:
  imagePullPolicy: "IfNotPresent"
  statefulEntities:
    - executorImage: "zacchaeus2000/executor-word-count:testv1.1"
      ioImage: "zacchaeus2000/iosidecar:testv1.1"
      stateImage: "zacchaeus2000/statesidecar:testv1.1"
      ioAddress: "host.docker.internal:9092"
      inputTopic: "input"
      outputTopic: "count"
      name: "word-count"
      pods:
        - name: "word-count-0"
          partitions:
            - "0,1,2"
          resources:
            requests:
              cpu: "128m"
            limits:
              cpu: "256m"
        - name: "word-count-1"
          partitions:
            - "3,4,5"
          resources:
            requests:
              cpu: "128m"
            limits:
              cpu: "256m"
    - executorImage: "zacchaeus2000/executor-sum:testv1.1"
      ioImage: "zacchaeus2000/iosidecar:testv1.1"
      stateImage: "zacchaeus2000/statesidecar:testv1.1"
      ioAddress: "host.docker.internal:9092"
      inputTopic: "count"
      outputTopic: "output"
      name: "sum"
      pods:
        - name: "sum-0"
          partitions:
            - "0"
          resources:
            requests:
              cpu: "256m"
            limits:
              cpu: "512m"
  version: "testv1"
  historyLimit: 3
